# Site settings
title: Welcome to Liu Xingchen's Homepage!
baseurl: 
url: 
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: LIU Xingchen
  desc: Doctor of Philosophy
  email: xingchenliu@u.nus.edu
  selfie: assets/img/202204232223133.jpg

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
#permalink: /:year-:month-:day/:title
#paginate_path: "/portfolio/page:num/"
#paginate: 5
#exclude:
  #
