project:
  type: website
  output-dir: docs
  
website:
  page-navigation: true
  title: "Xingchen Liu"
  site-url: https://xingchenliu666.github.io
  favicon: images/Xingchen Liu.jpg
  repo-url: https://github.com/xingchenliu666/xingchenliu666.github.io
  
  page-footer:
    left: |
      []()<br>
    right: |
      Made with [Quarto](https://quarto.org/)<br>
    
  navbar: 
    background: "#87301A"
    search: true
    right: 
      - text: "Home"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Miscellaneous"
        href: miscellaneous.qmd
      - text: "中文"
        href: Chinese.qmd

format:
  html:
    theme: styles.scss
    toc: true            # 启用目录
    toc-position: right  # 将目录放置在页面的右侧
    toc-depth: 3         # 设置目录的深度，数字越大，目录越详细